### ISSUE TITLE
csp-osgAL doesn't seem to build.

### ISSUE THREAD

**Issue by mikew02** [nsmoooose/csp#2]
Trying to build CSP again for nostalgic reasons on Fedora 26.
The readme instructions seems to go fine until 'make' on csp-osgAL where I encounter errors.
If there's some response here, I can add further details if needed.

**Comment by nsmoooose** [comment]
I will try to help you get it running. Please provide more info on the error.

I cannot always answer the same day though.

I also revisit this project from time to time for nostalgic reasons. I still dream on developing this thing. But I have very limited time do things like that.

/Henrik

**Comment by mikew02** [comment]
Thanks for the response! Obviously, not a huge priority but I'd appreciate the help. CSP has some interesting concepts, but all the sourceforge wiki stuff seems to have been lost. So, I don't know if it's possible to work out what does what. It's pleasing to see that you've rescued the source files at least...

Anyway, I'm running a fedora26 XFCE 64-bit spin .iso in VirtualBox. Once the VM is up and running, I run through your 'Linux build' instructions in the order given, adding cmake and g++ which seem to be missing.
When I get to the 'make' stage of the csp-osgAL part, I get this as the last bit of output. There are hundreds of exception handling warnings, but I don't know if they lead to the failure.
.
,
/home/mike/csp-osgal/include/openalpp/AudioEnvironment:152:25: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   void initiateReverb() throw (InitError);
                         ^~~~~
[ 62%] Linking CXX executable ../../bin/example_osgal
/bin/ld: CMakeFiles/example_osgal.dir/osgal.cpp.o: undefined reference to symbol '_ZTVN10__cxxabiv121__vmi_class_type_infoE@@CXXABI_1.3'
//usr/lib64/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [examples/osgal/CMakeFiles/example_osgal.dir/build.make:111: bin/example_osgal] Error 1
make[1]: *** [CMakeFiles/Makefile2:307: examples/osgal/CMakeFiles/example_osgal.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
[root@localhost csp-osgal]# 

There is a line after in the instructions:
"This will install osgAL in /usr/local/lib/. Make sure that this path is in your /etc/ld.so.conf.d/ somewhere."
...which may be a pre-requisite, but I don't know what to do about it.
Hopefully, this will be something stupid I'm doing, and not an indication that the entire code base needs rewriting to work with the latest libraries,gcc etc.

**Comment by nsmoooose** [comment]
My intention was to save the source code and try to fix compile issues. I have fixed a couple of issues since OpenSceneGraph sometimes introduces breaking changes with newer versions. So it shouldn't be too much work to get everything up and running for you.

We are both using Fedora 26 which is a good starting point. But I have not compiled the project in a year or so.

Things that I have looked at:
* I pushed a changeset to csp-osgal to remove all "warning: dynamic exception specifications". Please do a "git pull" in this repository to get the latest.
* Your error is with one of the example programs. These are building fine on my computer for some reason. You can skip compiling them if you toggle BUILD_EXAMPLES_OALPP and BUILD_EXAMPLES_OSGAL with "ccmake . " Toggle and do [c] configure and then [g] generate to create new make files. Please let me know if this helps. These are my dependencies found with ccmake http://bdcf4a0cc50ebef2.paste.se/


I also looked at the csp project itself.

There are some changes that needs to be pushed in order for it to compile there as well. I haven't finished that patch yet. (missing std:: in front of isnan, getBound -> getBoundingBox, something with osg::NodeCallback)

I will look into it again tomorrow.

/Henrik

**Comment by nsmoooose** [comment]
Create `/etc/ld.so.conf.d/local.conf` with the following content:
`/usr/local/lib`

And run `sudo ldconfig`

The above will allow programs to find locally installed libraries in /usr/local/lib. This is usually needed later when CSP is running in order to find libosgAL.so, libopenalpp.so etc

**Comment by mikew02** [comment]
Great! After getting your new osgAL files, the examples built OK this time...might be because I'm doing everything as root.
So, I now have successful 'scons config'. Thanks again!

**Comment by nsmoooose** [comment]
Pushed a changeset to the csp project as well with several fixes to compile with the latest gcc and OpenSceneGraph. Please do a "git pull".
Still a lot of compiler warnings though.

I successfully started the simulator as well!

Please let me know if you find any more issues.

/Henrik N

**Comment by mikew02** [comment]
Definitely getting there, but seem to be missing something. The compile process finished, but I get an error when trying to run. Here's the last few lines from my terminal:
scons: done building targets.
build time: 834 sec
[root@localhost csp]# ls
base  csp.dox  cspsim  data  examples     __init__.pyc  parser.out   SConstruct
bin   csplib   cspwf   dist  __init__.py  modules       parsetab.py  tools
[root@localhost csp]# cd bin
[root@localhost bin]# ls
IndexServer.ini  sim2.py  sim.ini  sim.py  sim-server.py  test_objects
[root@localhost bin]# ./sim.py
No module named _cspsim_module
Unable to import cspsim.py from csp/cspsim/.bin.  This file and
and others needed by cspsim are generated during the build.
Check that all targets have been built successfully.  See the
README file for build instructions.

**Comment by mikew02** [comment]
My fault! I forgot the 'sudo ldconfig'

**Comment by mikew02** [comment]
Been too busy flying around to close this issue. Thanks Henrik!

**Comment by nsmoooose** [comment]
Glad to hear it worked out for you!
Happy flying!

Don't hesitate to contact me again.

/Henrik N
